[fix] Tests
Since we choose to run the "chart-testing" container, as a non privileged user,
we rewrite Helm's repository-config and repository-cache directories, to /tmp .

This fixes errors such as:
    ```
    Error: Error installing charts: Error adding repo: incubator=https://charts.helm.sh/incubator: Error waiting for process: exit status 1
    Error installing charts: Error adding repo: incubator=https://charts.helm.sh/incubator: Error waiting for process: exit status 1
    ```